apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2026-02-18T13:46:37Z"
  deletionTimestamp: "2026-02-18T15:20:00Z"
  labels:
    kubernetes.io/metadata.name: traefik
  name: traefik
  resourceVersion: "386208"
  uid: 0b1a947b-b741-4ea3-90af-739be20e1a37
spec: {}
status:
  conditions:
  - lastTransitionTime: "2026-02-18T15:20:05Z"
    message: 'Discovery failed for some groups, 1 failing: unable to retrieve the
      complete list of server APIs: metrics.k8s.io/v1beta1: stale GroupVersion discovery:
      metrics.k8s.io/v1beta1'
    reason: DiscoveryFailed
    status: "True"
    type: NamespaceDeletionDiscoveryFailure
  - lastTransitionTime: "2026-02-18T15:20:07Z"
    message: All legacy kube types successfully parsed
    reason: ParsedGroupVersions
    status: "False"
    type: NamespaceDeletionGroupVersionParsingFailure
  - lastTransitionTime: "2026-02-18T15:20:07Z"
    message: All content successfully deleted, may be waiting on finalization
    reason: ContentDeleted
    status: "False"
    type: NamespaceDeletionContentFailure
  - lastTransitionTime: "2026-02-18T15:20:29Z"
    message: All content successfully removed
    reason: ContentRemoved
    status: "False"
    type: NamespaceContentRemaining
  - lastTransitionTime: "2026-02-18T15:20:29Z"
    message: All content-preserving finalizers finished
    reason: ContentHasNoFinalizers
    status: "False"
    type: NamespaceFinalizersRemaining
  phase: Terminating
